### ISSUE TITLE
SearchSectionTagsのprops設定

### ISSUE THREAD

**Issue by AAAR-Salmon** [oucrc-org/club-fes-2022#114]
pageのほうを煩雑にするのもあれなのでソート（優先するべきかどうか: `hasPriority`フィールド降順）もこっちでやってしまいましょう
あとは型もmicroCMSのほうに合わせたほうが楽ですね（`/types/cms/ITag.ts`にあります）

https://github.com/oucrc-org/club-fes-2022/blob/a3228aa20b20616b6b4e338114208ec48c717f69/types/cms/ITag.ts#L1-L5

**Comment by doanryo** [comment]
まだソートできてないので別PR作ります
